In [2]:
import pandas as pd

table1

## Read the tables

In [298]:
dhs = {
    'table1':pd.read_excel("./data/fy2017_table1.xlsx", header=3, skipfooter=2, na_values=['-','D']),
    'table2':pd.read_excel("./data/fy2017_table2.xlsx",header=3 ,skipfooter=24, na_values=['-','D']),
    'table3':pd.read_excel("./data/fy2017_table3d.xlsx",header=3 ,skipfooter=6, na_values=['-','D']),
    'table4':pd.read_excel("./data/fy2017_table4.xlsx",header=3, skipfooter=3, na_values=['-','D']),
    'table5':pd.read_excel("./data/fy2017_table5.xlsx", header=3, skipfooter=2, na_values=['-','D']),
    'table6':pd.read_excel("./data/fy2017_table6.xlsx",header=3, skipfooter=4, na_values=['-','D']),
    'table7':pd.read_excel("./data/fy2017_table7d.xlsx",header=3, skipfooter=3, na_values=['-','D']),
    'table8':pd.read_excel("./data/fy2017_table8.xlsx",header=3, skipfooter=2, na_values=['-','D']),
    'table9':pd.read_excel("./data/fy2017_table9d.xlsx", header=3, skipfooter=3, na_values=['-','D']),
    'table10':pd.read_excel("./data/fy2017_table10d.xlsx", header=3, skipfooter=4, na_values=['-','D']),
    'table11':pd.read_excel("./data/fy2017_table11d.xlsx", header=3, skipfooter=4, na_values=['-','D']),
    'table12':pd.read_excel("./data/fy2017_table12d.xlsx", header=3, skipfooter=4, na_values=['-','D']),
    'table13':pd.read_excel("./data/fy2016_table13.xls", header=3, skipfooter=2, na_values=['-','D']),
    'table14':pd.read_excel("./data/fy2016_table14d.xls", header=3, skipfooter=7, na_values=['-','D']),
    'table15':pd.read_excel("./data/fy2016_table15d.xls", header=3, skipfooter=4, na_values=['-','D']),
    'table16':pd.read_excel("./data/fy2016_table16.xls", header=3, skipfooter=1, na_values=['-','D']),
    'table17':pd.read_excel("./data/fy2016_table17d.xls", header=3, skipfooter=5, na_values=['-','D']),
    'table18':pd.read_excel("./data/fy2016_table18d.xls", header=3, skipfooter=5, na_values=['-','D']),
    'table19':pd.read_excel("./data/fy2016_table19d.xls", header=3, skipfooter=5, na_values=['-','D']),
    'table20':pd.read_excel("./data/fy2017_table20.xlsx", header = 5, skipfooter=6, na_values=['-','D']),
    'table21':pd.read_excel("./data/fy2017_table21d.xlsx", header = 3, skipfooter=6, na_values=['-','D']),
    'table22':pd.read_excel("./data/fy2017_table22.xlsx", header = 3, skipfooter=3, na_values=['-','D']),
    'table23':pd.read_excel("./data/fy2017_table23.xlsx", header=4, skipfooter=2, na_values=['-','D']),
    'table24':pd.read_excel("./data/fy2017_table24.xlsx", header=4, skipfooter=3, na_values=['-','D']),
    'table25':pd.read_excel("./data/fy2017_table25d.xlsx", header=2, skipfooter=10, na_values=['-','D']),
    'table26':pd.read_excel("./data/fy2017_table26d.xlsx", header=3, skipfooter=16, na_values=['-','D']),
    'table27':pd.read_excel("./data/fy2017_table27d.xlsx", header=3, skipfooter=9, na_values=['-','D']),
    'table28':pd.read_excel("./data/fy2017_table28d.xlsx", header=3, skipfooter=20, na_values=['-','D']),
    'table29':pd.read_excel("./data/fy2017_table29.xlsx", header=3, skipfooter=8, na_values=['-','D']),
    'table30':pd.read_excel("./data/fy2017_table30.xlsx", header=3, skipfooter=9, na_values=['-','D']),
    'table31':pd.read_excel("./data/fy2017_table31.xlsx", header=3, skipfooter=8, na_values=['-','D']),
    'table32':pd.read_excel("./data/fy2017_table32d.xlsx", header=3, skipfooter=16, na_values=['-','D'])
    }

In [311]:
descriptions = {
    "table1":"Persons Obtaining Lawful Permanent Resident Status: Fiscal Years 1820 to 2017",
    "table2":"Persons Obtaining Lawful Permanent Resident Status by Region and Selected Country of Last Residence: Fiscal Years 2015 to 2017",
    "table3":"Persons Obtaining Lawful Permanent Resident Status by Region and Country of Birth: Fiscal Years 2015 to 2017",
    "table4":"Persons Obtaining Lawful Permanent Resident Status by State or Territory of Residence: Fiscal Years 2015 to 2017",
    "table5":"Persons Obtaining Lawful Permanent Resident Status by Core Based Statistical Area (CBSA) of Residence: Fiscal Years 2015 to 2017",
    "table6":"Persons Obtaining Lawful Permanent Resident Status by Type and Major Class of Admission: Fiscal Years 2015 to 2017",
    "table7":"Persons Obtaining Lawful Permanent Resident Status by Type and Detailed Class of Admission: Fiscal Year 2017",
    "table8":"Persons Obtaining Lawful Permanent Resident Status by Sex, Age, Marital Status, and Occupation: Fiscal Year 2017",
    "table9":"Persons Obtaining Lawful Permanent Resident Status by Broad Class of Admission and Selected Demographic Characteristics: Fiscal Year 2017",
    "table10":"Persons Obtaining Lawful Permanent Resident Status by Broad Class of Admission and Region and Country of Birth: Fiscal Year 2017",
    "table11":"Persons Obtaining Lawful Permanent Resident Status by Broad Class of Admission and Region and Country of Last Residence: Fiscal Year 2017",
    "table12":"Immigrant Orphans Adopted by U.S. Citizens by Sex, Age, and Region and Country of Birth: Fiscal Year 2017",
    "table13":"Refugee Arrivals: Fiscal Years 1980 To 2016",
    "table14":"Refugee Arrivals By Region And Country Of Nationality: Fiscal Years 2014 To 2016",
    "table15":"Refugee Arrivals By Relationship To Principal Applicant And Sex, Age, And Marital Status: Fiscal Year 2016",
    "table16":"Individuals Granted Asylum Affirmatively Or Defensively: Fiscal Years 1990 To 2016",
    "table17":"Individuals Granted Asylum Affirmatively By Region And Country Of Nationality: Fiscal Years 2014 To 2016",
    "table18":"Individuals Granted Asylum Affirmatively By Relationship To Principal Applicant And Sex, Age, And Marital Status: Fiscal Year 2016",
    "table19":"Individuals Granted Asylum Defensively By Region And Country Of Nationality: Fiscal Years 2014 To 2016",
    "table20":"Petitions for Naturalization Filed, Persons Naturalized, and Petitions for Naturalization Denied: Fiscal Years 1907 to 2017",
    "table21":"Persons Naturalized by Region and Country of Birth: Fiscal Years 2015 to 2017",
    "table22":"Persons Naturalized by State or Territory of Residence: Fiscal Years 2015 to 2017",
    "table23":"Persons Naturalized by Core Based Statistical Area (CBSA) of Residence: Fiscal Years 2015 to 2017",
    "table24":"Persons Naturalized by Sex, Age, Marital Status, and Occupation: Fiscal Year 2017",
    "table25":"Nonimmigrant Admissions by Class of Admission: Fiscal Years 2015 to 2017",
    "table26":"Nonimmigrant Admissions (I-94 Only) by Region and Country of Citizenship: Fiscal Years 2015 to 2017",
    "table27":"Nonimmigrant Admissions (I-94 Only) by Region and Country of Residence: Fiscal Years 2015 to 2017",
    "table28":"Nonimmigrant Admissions (I-94 Only) by Selected Category of Admission and Region and Country of Citizenship: Fiscal Year 2017",
    "table29":"Nonimmigrant Admissions (I-94 Only) by Selected Category of Admission, Age, And Sex: Fiscal Year 2017",
    "table30":"Nonimmigrant Admissions (I-94 Only) by Selected Category of Admission and State or Territory of Destination: Fiscal Year 2017",
    "table31":"Nonimmigrant Admissions (I-94 Only) by Selected Category of Admission and Month of Arrival: Fiscal Year 2017",
    "table32":"Nonimmigrant Temporary Worker Admissions (I-94 Only) by Region and Country of Citizenship: Fiscal Year 2017"
}

In [308]:
def get_data_by_table_number(table_number):
    return dhs.get(f'table{table_number}')

In [309]:
def get_description_by_table_number(table_number):
    return dhs.get(f'table{table_number}')

    Region and country of birth     2008     2009     2010       2011  \
0                        REGION      NaN      NaN      NaN        NaN
1                         Total  1107126  1130818  1042625  1062040.0
2                        Africa   105915   127046   101355   100374.0
3                          Asia   399027   413312   422063   451593.0
4                        Europe   103782   105476    88801    83850.0
5                 North America   393196   375180   336553   333902.0
6                       Oceania     5263     5578     5345     4980.0
7                 South America    98549   102860    87178    86096.0
8                       Unknown     1394     1366     1330     1245.0
9                       COUNTRY      NaN      NaN      NaN        NaN
10                        Total  1107126  1130818  1042625  1062040.0
11                  Afghanistan     2813     3165     2017     1648.0
12                      Albania     5754     5137     4711     3612.0
13                      Algeria     1037     1485     1305     1364.0
14               American Samoa       14       19       14        NaN
15                       Angola      221      173      148      148.0
16                     Anguilla       22       21       19       25.0
17          Antigua and Barbuda      444      437      359      368.0
18                    Argentina     5353     5780     4399     4473.0
19                      Armenia     3586     3442     2979     2983.0
20                        Aruba       36       38       49       39.0
21                    Australia     2464     2622     2512     2343.0
22                      Austria      443      512      442      424.0
23                   Azerbaijan     1071      834      781      728.0
24                      Bahamas      682      751      652      668.0
25                      Bahrain       96      120      104      119.0
26                   Bangladesh    11753    16651    14819    16707.0
27                     Barbados      585      603      465      455.0
28                      Belarus     2390     2407     2038     1964.0
29                      Belgium      642      686      592      567.0
..                          ...      ...      ...      ...        ...
189                      Sweden     1019     1138     1097      979.0
190                 Switzerland      720      798      675      615.0
191                       Syria     2641     2442     2555     2785.0
192                      Taiwan     9073     8038     6732     6154.0
193                  Tajikistan      231      265      299      382.0
194                    Tanzania      838     2773     1850     1427.0
195                    Thailand     6637    10444     9384     9962.0
196                        Togo     1661     1680     1563     1506.0
197                       Tonga      365      379      343      408.0
198         Trinidad and Tobago     5937     6256     5435     5023.0
199                     Tunisia      410      416      418      440.0
200                      Turkey     4210     4958     4483     4403.0
201                Turkmenistan      274      290      224      260.0
202    Turks and Caicos Islands       35       31       29       33.0
203                      Uganda     1174     1364     1085     1239.0
204                     Ukraine    10813    11223     8477     8292.0
205        United Arab Emirates      693      697      779      707.0
206              United Kingdom    14348    15748    12792    11572.0
207               United States      216      181      201      269.0
208                     Uruguay     1451     1775     1331     1553.0
209                  Uzbekistan     6375     5467     4770     5056.0
210                   Venezuela    10514    11154     9409     9183.0
211                     Vietnam    31497    29234    30632    34157.0
212     Virgin Islands, British       53       46       46       37.0
213                       Yemen     1872     3134     3591     3361.0
214                      Zambia      613      704      628      652.0
215                    Zimbabwe      953      983     1274     1016.0
216       All other countries 2       30       38       32       27.0
217                     Unknown     1394     1366     1330     1245.0
218           NA Not available.      NaN      NaN      NaN        NaN

          2012      2013       2014       2015       2016       2017
0          NaN       NaN        NaN        NaN        NaN        NaN
1    1031631.0  990553.0  1016518.0  1051031.0  1183505.0  1127167.0
2     107241.0   98304.0    98413.0   101415.0   113426.0   118824.0
3     429599.0  400548.0   430508.0   419297.0   462299.0   424743.0
4      81671.0   86556.0    83266.0    85803.0    93567.0    84335.0
5     327771.0  315660.0   324354.0   366126.0   427293.0   413650.0
6       4742.0    5277.0     5112.0     5404.0     5588.0     5071.0
7      79401.0   80945.0    73715.0    72309.0    79608.0    79076.0
8       1206.0    3263.0     1150.0      677.0     1724.0     1468.0
9          NaN       NaN        NaN        NaN        NaN        NaN
10   1031631.0  990553.0  1016518.0  1051031.0  1183505.0  1127167.0
11      1617.0    2196.0    10527.0     8328.0    12513.0    19538.0
12      3364.0    3186.0     3828.0     4653.0     5773.0     5722.0
13      1369.0    1241.0     1669.0     1775.0     2180.0     2139.0
14         NaN       NaN        NaN        NaN        NaN        NaN
15       187.0     143.0      148.0      154.0      198.0      209.0
16        23.0      22.0       20.0       22.0       20.0       23.0
17       337.0     344.0      369.0      290.0      324.0      322.0
18      4359.0    4372.0     3874.0     3730.0     4091.0     3482.0
19      2681.0    2722.0     2913.0     2962.0     3543.0     3437.0
20        54.0      45.0       40.0       38.0       23.0       47.0
21      2414.0    2759.0     2809.0     3034.0     3239.0     2906.0
22       407.0     415.0      438.0      474.0      432.0      387.0
23       663.0     637.0      672.0      676.0      784.0      881.0
24       619.0     630.0      654.0      725.0      656.0      725.0
25       104.0     115.0      122.0      145.0      138.0      130.0
26     14705.0   12099.0    14645.0    13570.0    18723.0    14693.0
27       460.0     428.0      384.0      376.0      371.0      373.0
28      1659.0    1970.0     2015.0     1994.0     2127.0     1919.0
29       574.0     675.0      632.0      662.0      691.0      625.0
..         ...       ...        ...        ...        ...        ...
189      968.0    1106.0      954.0     1066.0     1144.0      950.0
190      635.0     697.0      656.0      640.0      743.0      565.0
191     3014.0    3366.0     3540.0     3840.0     4800.0     5877.0
192     5331.0    5385.0     4697.0     4888.0     5120.0     4858.0
193      411.0     550.0      516.0      595.0      593.0      652.0
194     1516.0     837.0      774.0      799.0      788.0     1415.0
195     9459.0    7583.0     6197.0     7502.0     7039.0     6311.0
196     1756.0    1257.0     1612.0     1547.0     1938.0     1572.0
197      276.0     348.0      320.0      327.0      283.0      262.0
198     5214.0    4724.0     3988.0     3212.0     3469.0     3100.0
199      422.0     445.0      429.0      518.0      518.0      535.0
200     4162.0    4144.0     3834.0     4201.0     4469.0     4844.0
201      223.0     210.0      254.0      226.0      235.0      251.0
202       30.0      50.0       40.0       38.0       39.0       35.0
203     1340.0    1350.0     1409.0     1664.0     1649.0     1898.0
204     7642.0    8193.0     7752.0     7987.0    10422.0    10135.0
205      854.0     910.0     1039.0     1193.0     1370.0     1314.0
206    12014.0   12984.0    12225.0    12592.0    12673.0    10948.0
207      279.0     319.0      358.0      370.0      468.0      409.0
208     1374.0    1352.0     1128.0     1078.0      972.0     1001.0
209     4726.0    4382.0     5194.0     3977.0     4359.0     4095.0
210     9387.0    9572.0     8427.0     9144.0    10772.0    11809.0
211    28304.0   27101.0    30283.0    30832.0    41451.0    38231.0
212       39.0      45.0       56.0       38.0       40.0       25.0
213     2620.0    3532.0     3492.0     3194.0    13040.0     6029.0
214      643.0     505.0      441.0      460.0      487.0      537.0
215      914.0     924.0      797.0      779.0      815.0      810.0
216       25.0      30.0       36.0       35.0       34.0       37.0
217     1206.0    3263.0     1150.0      677.0     1724.0     1468.0
218        NaN       NaN        NaN        NaN        NaN        NaN

[219 rows x 11 columns]

None